name: "Run"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12-15 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0 
    - name: Commit & Push changes
      uses: actions-js/push@main
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        empty: true
        message: "Stats Updated"
        author_email: "krishchoudhary2126@gmail.com"
        author_name: "Krishna Choudhary"
        branch: "main"
